### ISSUE TITLE
EXC_BAD_ACCESS and Error message

### ISSUE THREAD

**Issue by terhechte** [matthijs2704/vapor-apns#8] opened 2016-10-11 20:31 UTC
Hey,

I'm currently developing a small application with vapor-apns and I just ran into an issue which crashed the vapor server with an exc_bad_access.

I'm not entirely sure what happened, but it may be (or not) related to the iOS app which receives the push notification restarting. Here's my setup:
- I have Vapor sending out push notifications running locally (started in Xcode)
- I have an iOS app receiving push notifications running on the same wifi as vapor (started in Xcode)
- Vapor sends out a silent push notification to the iOS app
- This worked fine during several tests.
- I restarted the iOS app in Xcode while vapor was still sending push notifications.
- Vapor-apns logged the following error:
  "error: This error has not been mapped yet in APNSError: Failed initialisation"
- Vapor crashed in VaporAPNS.swift line 111 with EXC_BAD_ACCESS

Attached is a screenshot of the error environment.

Cheers & Thanks & Keep up the good work!
<img width="1140" alt="screen shot 2016-10-11 at 22 30 44" src="https://cloud.githubusercontent.com/assets/132234/19287566/714b13f6-9002-11e6-991f-45a2b6b35f8d.png">

**Comment by matthijs2704** [comment] 2016-10-11 20:39
Hey! Thanks for your issue :)

Hmm I'm thinking it might has to do with the way Xcode debugging is handled. Could you try relaunching the app from your Springboard (homescreen of your iOS device) instead of launching it using Xcode, to see if it's also happening when doing it that way?

Thanks!

**Comment by terhechte** [comment] 2016-10-11 20:40
Thanks for the quick reply! Sure, will test that tomorrow.

**Comment by matthijs2704** [comment] 2016-10-11 20:42
@terhechte Awesome, thanks!

**Comment by nickskull** [comment] 2016-10-19 09:45
@terhechte Hey, any updates on this? :) I've been experiencing same kind of crashes, although in a different part of the codebase, but I was wondering if it was related somehow before opening a new issue :)

**Comment by matthijs2704** [comment] 2016-10-19 10:10
@nickskull Just open a new issue for it ;) If i's a duplicate we can always close it!

**Comment by matthijs2704** [comment] 2016-10-31 17:46
@terhechte Any updates on this? :)

**Comment by matthijs2704** [comment] 2016-11-05 22:30
@terhechte @nickskull any of you got updates on this? More tests? I'm not able to reproduce the error here...

**Comment by nickskull** [comment] 2016-11-09 21:41
@matthijs2704 Actually my issue is the exact same one as described by @terhechte. Will see if I can find a fix :) Otherwise I'll post a project where you can replicate.

**Comment by matthijs2704** [comment] 2017-03-19 10:28
Closing this for now due to inactivity. Feel free to reopen if you're still experiencing this issue!

**Closed by matthijs2704** 2017-03-19 10:28 UTC
Labels: bug
